#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ cf4k8s = library.get("cf-for-k8s")

#@ chain = cf4k8s.eval()

#@ for extension in data.values.cffork8s.extension_points.example_extension_point:
#@ lib = library.get(extension.extension.library)
#@ chain = overlay.apply(chain, lib.export(extension.extension.overlay)())
#@ end
--- #@ template.replace(chain)

